prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix sn: <http://snomedtools.info/snomed/term/>



DELETE {
?desc rdfs:label ?label.
}
INSERT {
?desc rdfs:label "Mollusc"@en-gb.
}
WHERE 
{
   bind (<http://snomedtools.info/snomed/version/1/description/rdfs/1219322012>
        as ?desc)
    
 OPTIONAL {?desc rdfs:label ?label.}	
} 