prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix sn: <http://sct.snomed.info/>

SELECT ?p ?j
WHERE 
{
   
   bind (<http://sct.snomed.info/106877009>
        as ?s)
    
	?s rdfs:subClassOf ?p.
    ?p ?prop ?j.
    ?p rdfs:label "Kingdom Animalia (organism)"@en-gb.
} 