#retrieves resource and label  of Concept 1910005, its children and their children
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix sn: <http://snomed.info/sct/term/>
prefix fn: <http://www.w3.org/2005/xpath-functions#>

SELECT ?p ?g ?label
 
WHERE 
{
   
   bind (<http://snomed.info/sct/version/1/concept/rdfs/1910005>
        as ?s)
    {
    	?s ^rdfs:subClassOf ?p.
    }
    UNION 
    {
    	?s ^rdfs:subClassOf ?g.
    	?g ^rdfs:subClassOf ?p.
    	
    }
	?p rdfs:label ?label.
	
	
} 

LIMIT 200