prefix xsd: <http://www.w3.org/2001/XMLSchema#>
#retrieves resource and label  of Concept 106877009, its children and their children
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix sn: <http://snomedtools.info/snomed/term/>
prefix fn: <http://www.w3.org/2005/xpath-functions#>

SELECT ?p ?g ?label ?effectiveDate
 
WHERE 
{
   
   bind (<http://snomedtools.info/snomed/version/1/concept/rdfs/106877009>
        as ?s)
    #concept 106877009 children
    {
    	?s ^rdfs:subClassOf ?p.

    }
    #Child's children
    UNION 
    {
    	?s ^rdfs:subClassOf ?g.
    	?g ^rdfs:subClassOf ?p.
    }
	?p rdfs:label ?label.
    ?p sn:effectiveTime ?effectiveDate.
   FILTER (xsd:dateTime(?effectiveDate) > "2002-01-30T00:00:00Z"^^xsd:dateTime ) .
} 

LIMIT 200