#retrieves all property of Concept 1910005, its parent and grand parent
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix sn: <http://snomedtools.info/snomed/term/>

			
			
CONSTRUCT 
{
    ?s ?prop ?o.
  	?s rdfs:subClassOf ?p.

  	?p ?pProp ?op.
  	?p rdfs:subClassOf ?gp.
  
   	?gp ?gProp ?ogp.
} 
WHERE 
{
   
   bind (<http://snomedtools.info/snomed/version/1/concept/rdfs/106877009>
        as ?s)
    
    ?s ?prop ?o.
               	
	?s rdfs:subClassOf ?p.
	?p ?pProp ?op.
	?p rdfs:subClassOf ?gp.
	
 	?gp ?gProp ?ogp.
	
} 